# Generated by Django 3.0.2 on 2020-04-22 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('phone1', models.CharField(max_length=255)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'เปิดร้าน'), (2, 'ปิดร้าน')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date_review', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'ธรรมดา'), (2, 'พรีเมี่ยม')], default=1)),
                ('gene', models.IntegerField(choices=[(1, 'ทุเรียนภูเขาไฟ'), (2, 'ก้านยาว'), (3, 'หมอนทอง'), (4, 'ชะนี'), (5, 'กระดุม'), (6, 'หลงลับแล'), (7, 'พวงมณี')], default=1)),
                ('values', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('desc', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'ขาย'), (2, 'สิ้นค้าหมด')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Store')),
            ],
        ),
    ]
