# Generated by Django 3.0.2 on 2020-04-23 13:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
