# Generated by Django 3.0.2 on 2020-04-24 05:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20200423_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_regis', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('food_storage_license', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('gmp_regis', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('otop_regis', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Store')),
            ],
        ),
    ]
