# Generated by Django 3.0.2 on 2020-04-26 04:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_storecertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecertificate',
            name='commercial_regis',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Commercial Registraion'),
        ),
        migrations.AlterField(
            model_name='storecertificate',
            name='food_storage_license',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Food Storage License'),
        ),
        migrations.AlterField(
            model_name='storecertificate',
            name='gmp_regis',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='GMP Certificate'),
        ),
        migrations.AlterField(
            model_name='storecertificate',
            name='otop_regis',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='OTOP Certificate'),
        ),
    ]
