# Generated by Django 3.0.2 on 2020-05-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_bookbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.Product'),
            preserve_default=False,
        ),
    ]
