# Generated by Django 3.0.2 on 2020-05-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20200503_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'พร้อมขาย'), (2, 'สั่งจองล่วงหน้า'), (3, 'ยุติการขาย')], default=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.IntegerField(choices=[(0, 'รอการอนุมัติ'), (1, 'เปิดร้าน'), (2, 'ปิดร้าน')], default=0),
        ),
    ]
