# Generated by Django 3.1.7 on 2021-04-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20200605_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='product_imgs'),
        ),
    ]
