# Generated by Django 3.1.7 on 2021-04-25 14:47

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_auto_20210424_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to=Store.models.PathAndRename('uploads/product_imgs')),
        ),
    ]
