# Generated by Django 3.1.7 on 2021-05-03 09:41

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_socialqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialqrcode',
            name='qr_code',
            field=models.ImageField(upload_to=Store.models.PathAndRename('uploads/qrcode_img')),
        ),
    ]
