# Generated by Django 3.2.12 on 2023-06-01 08:16

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_alter_store_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=255)),
                ('product_desc', models.TextField()),
                ('rec_product_img', models.ImageField(upload_to=Store.models.PathAndRename('uploads/rec_product_imgs'))),
                ('link', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'RecommendedProduct',
                'verbose_name_plural': 'RecommendedProducts',
            },
        ),
    ]
