# Generated by Django 3.2.12 on 2023-06-01 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_alter_recommendedproduct_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedproduct',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
