# Generated by Django 3.0.2 on 2020-04-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_news_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.IntegerField(choices=[(0, 'เผยแพร่'), (1, 'ไม่เผยแพร่')], default=0),
        ),
    ]
