# Generated by Django 3.0.2 on 2020-04-27 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0002_auto_20200426_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('province', models.IntegerField(choices=[(1, 'กรุงเทพมหานคร'), (2, 'สมุทรปราการ'), (3, 'นนทบุรี'), (4, 'ปทุมธานี'), (5, 'พระนครศรีอยุธยา'), (6, 'อ่างทอง'), (7, 'ลพบุรี'), (8, 'สิงห์บุรี'), (9, 'ชัยนาท'), (10, 'สระบุรี'), (11, 'ชลบุรี'), (12, 'ระยอง'), (13, 'จันทบุรี'), (14, 'ตราด'), (15, 'ฉะเชิงเทรา'), (16, 'ปราจีนบุรี'), (17, 'นครนายก'), (18, 'สระแก้ว'), (19, 'นครราชสีมา'), (20, 'บุรีรัมย์'), (21, 'สุรินทร์'), (22, 'ศรีสะเกษ'), (23, 'อุบลราชธานี'), (24, 'ยโสธร'), (25, 'ชัยภูมิ'), (26, 'อำนาจเจริญ'), (27, 'หนองบัวลำภู'), (28, 'ขอนแก่น'), (29, 'อุดรธานี'), (30, 'เลย'), (31, 'หนองคาย'), (32, 'มหาสารคาม'), (33, 'ร้อยเอ็ด'), (34, 'กาฬสินธุ์'), (35, 'สกลนคร'), (36, 'นครพนม'), (37, 'มุกดาหาร'), (38, 'เชียงใหม่'), (39, 'ลำพูน'), (40, 'ลำปาง'), (41, 'อุตรดิตถ์'), (42, 'แพร่'), (43, 'น่าน'), (44, 'พะเยา'), (45, 'เชียงราย'), (46, 'แม่ฮ่องสอน'), (47, 'นครสวรรค์'), (48, 'อุทัยธานี'), (49, 'กำแพงเพชร'), (50, 'ตาก'), (51, 'สุโขทัย'), (52, 'พิษณุโลก'), (53, 'พิจิตร'), (54, 'เพชรบูรณ์'), (55, 'ราชบุรี'), (56, 'กาญจนบุรี'), (57, 'สุพรรณบุรี'), (58, 'นครปฐม'), (59, 'สมุทรสาคร'), (60, 'สมุทรสงคราม'), (61, 'เพชรบุรี'), (62, 'ประจวบคีรีขันธ์'), (63, 'นครศรีธรรมราช'), (64, 'กระบี่'), (65, 'พังงา'), (66, 'ภูเก็ต'), (67, 'สุราษฎร์ธานี'), (68, 'ระนอง'), (69, 'ชุมพร'), (70, 'สงขลา'), (71, 'สตูล'), (72, 'ตรัง'), (73, 'พัทลุง'), (74, 'ปัตตานี'), (75, 'ยะลา'), (76, 'นราธิวาส'), (77, 'บึงกาฬ')])),
                ('postcode', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receive_address', models.ManyToManyField(to='Cart.ReceiveAddress')),
            ],
        ),
    ]
