# Generated by Django 3.0.2 on 2020-04-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_addressbook_receiveaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveaddress',
            name='phone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiveaddress',
            name='receiver',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
