# Generated by Django 3.0.2 on 2020-04-27 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20200426_1123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0004_auto_20200427_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'รอรับออร์เดอร์'), (2, 'รับออร์เดอร์แล้ว'), (3, 'รอการชำระเงิน'), (4, 'ชำระเงินแล้ว'), (5, 'ชำระเงินแล้ว'), (6, 'จัดส่งสินค้าแล้ว'), (7, 'ดำเนินการเสร็จสิ้น')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receive_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.ReceiveAddress')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Store')),
            ],
        ),
    ]
