# Generated by Django 3.0.2 on 2020-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_auto_20200427_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'รอรับออร์เดอร์'), (2, 'รับออร์เดอร์แล้ว'), (3, 'รอการชำระเงิน'), (4, 'ชำระเงินแล้ว'), (5, 'ชำระเงินแล้ว'), (6, 'จัดส่งสินค้าแล้ว'), (7, 'ดำเนินการเสร็จสิ้น'), (8, 'ยกเลิก')], default=1),
        ),
    ]
