# Generated by Django 3.0.2 on 2020-05-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_auto_20200501_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernotification',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
