# Generated by Django 3.0.2 on 2020-05-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_bookbank'),
        ('Cart', '0009_auto_20200501_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfernotification',
            name='bookbank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.BookBank'),
            preserve_default=False,
        ),
    ]
