# Generated by Django 3.0.2 on 2020-05-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0010_transfernotification_bookbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
