# Generated by Django 3.0.2 on 2020-05-15 14:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0011_order_customer_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernotification',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
