# Generated by Django 3.0.2 on 2020-05-15 14:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_auto_20200515_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernotification',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
