# Generated by Django 3.0.2 on 2020-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0013_auto_20200515_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernotification',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
