# Generated by Django 3.0.2 on 2020-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0016_ordermessage_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
