# Generated by Django 3.0.2 on 2020-05-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_auto_20200506_1104'),
        ('Cart', '0017_ordertracking_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.Store'),
            preserve_default=False,
        ),
    ]
