# Generated by Django 3.0.2 on 2020-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0019_orderitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
