# Generated by Django 3.0.2 on 2020-05-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0020_orderitem_price_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxsize_1', models.IntegerField(default=1)),
                ('boxsize_2', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.Order')),
            ],
        ),
    ]
