# Generated by Django 3.0.2 on 2020-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0021_orderbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='box_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='box_2',
            field=models.IntegerField(default=0),
        ),
    ]
