# Generated by Django 3.1.7 on 2021-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0022_auto_20200530_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernotification',
            name='image',
            field=models.ImageField(upload_to='slip_imgs'),
        ),
    ]
