# Generated by Django 3.1.7 on 2021-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0023_auto_20210424_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernotification',
            name='image',
            field=models.ImageField(upload_to='uploads/slip_imgs'),
        ),
    ]
