# Generated by Django 3.1.7 on 2021-04-25 14:57

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0024_auto_20210424_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernotification',
            name='image',
            field=models.ImageField(upload_to=Store.models.PathAndRename('uploads/slip_imgs')),
        ),
    ]
