# Generated by Django 3.0.2 on 2020-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='trader_type',
            field=models.CharField(choices=[('เจ้าของสวน', 'เจ้าของสวน'), ('ผู้ค้าคนกลาง', 'ผู้ค้าคนกลาง')], max_length=50),
        ),
    ]
