# Generated by Django 3.0.2 on 2020-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_auto_20200421_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='citizen_id',
            field=models.CharField(max_length=13),
        ),
    ]
