# Generated by Django 3.0.2 on 2020-04-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_auto_20200421_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='owner',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
