# Generated by Django 3.2.12 on 2022-02-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_auto_20200422_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
