# Generated by Django 3.2.12 on 2023-06-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_alter_trader_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('moo', models.CharField(max_length=10)),
                ('subdistrict', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('ผู้ผลิต', 'ผู้ผลิต'), ('ผู้ประกอบการ', 'ผู้ประกอบการ'), ('ผู้ผลิตและผู้ประกอบการ', 'ผู้ผลิตและผู้ประกอบการ')], max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'verbose_name': 'registerGI',
                'verbose_name_plural': 'registerGIs',
            },
        ),
    ]
